
---

server:
    port: 1301
    
spring:
    profiles: default
    application:
        name: config-client
    
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:2002/eureka/

info:
    des: 这是默认的默认的default
    author: x2yu